admin: 'Browser_Administrator'
readOnly: 'Browser_ReadOnly'
bridgeEditor: 'Browser_BridgeEditor'
readWrite: 'Browser_ReadWrite'
roadScheduleEditor: 'Browser_RoadScheduleEditor'
programmeSubmitter: 'Browser_ProgrammeSubmitter'
unlocker: 'Browser_Unlocker'
missingEdgeResolver: 'Browser_MissingEdgeResolver'
canAccess: 'Browser_CanAccess'
psciEditor: 'Browser_PSCIEditor'
la16Coordinator: 'Browser_LA16Coordinator'
la16Surveyor: 'Browser_LA16Surveyor'
