percent: ["Percentage", "number"]
money: ["Money (€)", "number"]
area: ["Area", "number"]
meters: ["Meters", "number"]
millimeters: ["Millimeters", "number"]
speed: ["Speed (km/h)", "number"]
volume: ["Volume", "number"]
rating: ["PSCI Rating", "number"]
boolean: ["Boolean (Yes/No)", "boolean"]
string: ["String", "string"]
double: ["Double", "number"]
coordinate: ["Coordinate", "number"]
integer: ["Whole Number", "number"]
number: ["Whole Number", "number"]
date: ["Date (d/m/Y)", "date"]
EngineeringInspection: ["Bridges Engineering", "string"]
MaintenanceInspection: ["Bridges Maintenance", "string"]
PhaseColumn: ["LA16 Phase", "string"]